spring.application.name=CryptoFin Dashboard

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cryptofin
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Server
server.port=8080

# Scheduler
app.scheduler.enabled=true
app.coins.top-count=50

# CoinGecko API
app.coingecko.base-url=https://api.coingecko.com/api/v3

# NBU API
app.nbu.base-url=https://bank.gov.ua/NBUStatService/v1/statdataretrieve/exchange
